server:
  ssl:
    enabled: true
    key-store: file:/root/ssl/keystore.jks
    key-store-password: vinorate-ssl
    key-store-type: JKS
    key-alias: vinorate.ru
    key-password: vinorate-ssl
  port: 443

spring:
  application:
    name: vinorate
  datasource:
    url: jdbc:postgresql://db:5432/vinorate
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none