version: "3"
networks:
  web:
    external:
      name: web

services:
  vinorate:
    networks:
      web: null
    build: .
    container_name: vinorate
    environment:
      JAVA_OPTS: -XX:+UseContainerSupport -Xmx512m
    ports:
      - 443:443
    restart: always
    depends_on:
      - db
  db:
    networks:
      web: null
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=mutalking
      - POSTGRES_PASSWORD=PostgresMuTalKing123!@#
      - POSTGRES_DB=vinorate
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    restart: always