version: "3"
networks:
  web:
    external:
      name: web

services:
  vinorate:
    networks:
      web: null
    build: .
    container_name: vinorate
    environment:
      JAVA_OPTS: -XX:+UseContainerSupport -Xmx512m
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    networks:
      web: null
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vinorate
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    restart: always

  pgadmin:
    networks:
      web: null
    container_name: pgadmin4_container
    image: dpage/pgadmin4:6.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"

  selenoid:
    networks:
      web: null
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    volumes:
      - ./selenoid:/etc/selenoid:ro
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/path/to/config/video:/opt/selenoid/video"
      - "/path/to/config/logs:/opt/selenoid/logs"
    command: ["-container-network", "web", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    networks:
      web: null
    image: aerokube/selenoid-ui
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]